package callisto_editor_common

GALI_SPEC_VERSION_MAJOR :: 0
GALI_SPEC_VERSION_MINOR :: 0
GALI_SPEC_VERSION_PATCH :: 1


CONSOLE_COLOR_RED    :: "\u001b[31m"
CONSOLE_COLOR_GREEN  :: "\u001b[32m"
CONSOLE_COLOR_YELLOW :: "\u001b[33m"
CONSOLE_COLOR_RESET  :: "\u001b[0m"
